### ISSUE TITLE
Image thumbnail wrong color

### ISSUE THREAD

**Issue by Ali-RS** [thebombzen/jxlatte#12]
When I convert bench.jxl file (from samples) to png the thumbnail color looks wrong.

![Screenshot_2023-04-03_20-13-04](https://user-images.githubusercontent.com/5787647/229560165-f773a9db-d92e-4156-93ef-bf8ca96be260.png)

The original image looks like this:

![bench](https://user-images.githubusercontent.com/5787647/229560647-afa92fbd-2b2f-49dd-ad5a-12308f40ad4c.png)

**Comment by thebombzen** [comment]
That's because your thumbnailer doesn't respect the ICC profile of the resulting image. This has nothing to do with jxlatte.
