### ISSUE TITLE
Visual Defect: Quality 0 image decoded wrong

### ISSUE THREAD

**Issue by hYdos** [thebombzen/jxlatte#15]
![image](https://user-images.githubusercontent.com/25501603/230747176-c6d540b4-56c2-460e-8aa9-c488992ddd57.png)
https://cdn.discordapp.com/attachments/1080332031914950716/1094408594344132739/body_a_emi.jxl

**Comment by thebombzen** [comment]
This happens because you're interpreting an RGBA buffer as RGB.
