### ISSUE TITLE
Support Java virtual threads

### ISSUE THREAD

**Issue by Ali-RS** [thebombzen/jxlatte#16]
Hi

As you may know in newer Java versions they added support for "virtual threads". Is it possible to add an option for enabling virtual threads to be used instead of hardware threads? (for those who are using newer Java versions) 

Possibly via a thread supplier Function or something.

**Comment by thebombzen** [comment]
I use `Executors::newWorkStealingThreadPool` in order to parallelize, rather than `Thread` objects themselves, so changing it to a virtual threading interface shouldn't be too difficult, as I just have to change what ExecutorService I create.

**Comment by Ali-RS** [comment]
Nice, 

For using virtual threads `Executors.newVirtualThreadPerTaskExecutor()` could be used.

**Comment by thebombzen** [comment]
I just tested the difference between the two, and there was no measurable improvement, so I don't think it's worth breaking compatibility for this.

**Comment by Ali-RS** [comment]
>so I don't think it's worth breaking compatibility for this.

No compatibility breaking would happen I think

https://github.com/thebombzen/jxlatte/blob/21f5ab01dfa1dd2d760f464b2972540ec80322c8/java/com/thebombzen/jxlatte/util/FlowHelper.java#L45-L47

Just need to add a new constructor

```
    public FlowHelper(Supplier<ExecutorService> supplier) {
        threadPool = supplier.get();
    }
```

So users can be able to provide their custom suppliers.

**Comment by thebombzen** [comment]
See: 53dca9853d94fbddd2fcf10b521d5b1a37a850ec
