### ISSUE TITLE
Visual glitches exporting JXL to PNG

### ISSUE THREAD

**Issue by langurmonkey** [thebombzen/jxlatte#2]
Testing around the conversion from JXL to PNG yields wee glitches in the form of wrongly colored pixels and/or wrong columns. See attached converted PNG (*.jxl.png). Unfortunately, GitHub does not seem to support attaching JXL, so I'm attaching the original PNG from which the JXL was encoded.

Original PNG:
![vt-lod](https://user-images.githubusercontent.com/1049893/216432130-ac66e863-2e96-4add-b509-2d5b07c49d9f.png)

PNG ->(gimp) JXL ->(jxlatte) PNG
![vt-lod jxl](https://user-images.githubusercontent.com/1049893/216432223-5835d0e1-3513-47ea-beee-d0ea771324db.png)

**Comment by thebombzen** [comment]
Please attach the JXL so I can test it. (You can actually attach it, you just have to rename it to something supported like `.jpg`. Yes really.)

**Comment by langurmonkey** [comment]
Nice trick, here it is.
![cubes jxl](https://user-images.githubusercontent.com/1049893/216616491-2b5f9448-cd26-44c8-beb3-de2d64085db6.jpg)

**Comment by thebombzen** [comment]
Fixed in 5b02554f9ab01134b7a19c1182f81b366fd3bcd1.

**Comment by langurmonkey** [comment]
Awesome, works perfectly now!
