### ISSUE TITLE
Add support for decoding into Java ImageIO BufferedImage

### ISSUE THREAD

**Issue by Ali-RS** [thebombzen/jxlatte#7]
Hi,

Thanks for providing this library

It would be nice to add a utility class for converting JXLImage to java BufferedImage. 
Or even better would be to add an ImageIO plugin so we can directly load via ImageIO. 

What do you think?

**Comment by thebombzen** [comment]
Adding a method to convert from `JXLImage` to `BufferedImage` would be possible, but I don't know how to add an ImageIO plugin.

**Comment by Ali-RS** [comment]
Thanks, adding a convert method would be enough for my use case.

**Comment by hYdos** [comment]
> Adding a method to convert from `JXLImage` to `BufferedImage` would be possible, but I don't know how to add an ImageIO plugin.

github.com/The-PokeCraft-Mod/jxlatte/ 
Learn From this quick impl

**Comment by thebombzen** [comment]
Implemented in f635efff05082078979d62a2893ca6890a3b00ba
