### ISSUE TITLE
Publish artifacts to GitHub release or Maven Central

### ISSUE THREAD

**Issue by Ali-RS** [thebombzen/jxlatte#8]
Hi,

Can you please publish the prebuilt artifacts to the GitHub release page or Maven Central? (Possibly using GitHub actions)

**Comment by hYdos** [comment]
@thebombzen This is why we need either Gradle (build.gradle or build.gradle.kts) or Maven. (pom.xml) (you pick, I honestly don't care how you do it, It just needs to get done)

**Comment by thebombzen** [comment]
It doesn't *need* to get done. You can add a jar to your classpath like any library.

**Comment by hYdos** [comment]
If you want to take this seriously and get people to actually be able to use it with a proper build system, You do need to do it. Adding it to the classpath from a jar is some C level poor design
